#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

#ddev import-db --src=.project/data/db.sql.gz
mkdir -p config/sites/main && cp config/sites/config.yaml config/sites/main/
ddev typo3 install:setup
mkdir -p .Build/public/fileadmin
#cd .Build/public/ && tar xf ../../.project/data/fileadmin.tar.gz
